apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      # Scrape configuration for Kubernetes nodes (default)
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:10255'
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      # Scrape configuration for Kubernetes service endpoints (for backend)
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: (.+)
            action: keep

          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance

          - source_labels: [__meta_kubernetes_service_label_app]
            regex: receipt-backend
            replacement: /actuator/prometheus
            target_label: __metrics_path__
            action: replace

          - source_labels: [__meta_kubernetes_service_label_app]
            regex: receipt-frontend
            replacement: /metrics
            target_label: __metrics_path__
            action: replace

          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            regex: '(.+):(\d+);(\d+)'
            replacement: '${1}:${3}'
            target_label: __address__
            action: replace

          - source_labels: [__address__]
            regex: '(.+):(\d+)'
            replacement: '${1}:${2}'
            target_label: __address__
            action: replace

          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - action: labelmap
            regex: __meta_kubernetes_pod_annotation_(.+)
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - action: replace
            source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_service_name

      # NEW: Scrape configuration for pods using annotations (for frontend)
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            target_label: __metrics_path__
            regex: (.+)
            replacement: $1
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            target_label: __address__
            regex: (.+);(.+)
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
