name: Deploy Minimal Pod Monitoring
on:
  workflow_dispatch:

env:
  GKE_CLUSTER_NAME: receipt-dev-cluster
  GKE_REGION: us-central1
  NAMESPACE: dev

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: eadtud
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_REGION

    # Deploy main monitoring stack
    - name: Deploy Monitoring Stack
      run: |
        kubectl apply -f Monitoring/graphana-prometheus-stack.yaml -n $NAMESPACE

    # Add additional Grafana dashboards
    - name: Deploy Additional Grafana Dashboards
      run: |
        cat <<EOF | kubectl apply -n $NAMESPACE -f -
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: grafana-dashboards
          labels:
            app: grafana
        data:
          pod-status.json: |-
            {
              "title": "Pod Status Monitor",
              "tags": ["kubernetes", "pods"],
              "timezone": "browser",
              "panels": [
                {
                  "title": "Pod Status Overview",
                  "type": "stat",
                  "datasource": "Prometheus",
                  "gridPos": {"x": 0, "y": 0, "w": 24, "h": 8},
                  "targets": [
                    {
                      "expr": "up{job='receipt-backend'} or up{job='receipt-frontend'}",
                      "legendFormat": "{{pod}}",
                      "refId": "A"
                    }
                  ],
                  "options": {
                    "colorMode": "value",
                    "graphMode": "area",
                    "justifyMode": "auto",
                    "orientation": "auto",
                    "reduceOptions": {
                      "calcs": ["lastNotNull"],
                      "fields": "",
                      "values": false
                    },
                    "textMode": "auto"
                  },
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "thresholds"
                      },
                      "thresholds": {
                        "mode": "absolute",
                        "steps": [
                          {"color": "red", "value": null},
                          {"color": "green", "value": 1}
                        ]
                      }
                    }
                  }
                }
              ]
            }
        EOF

    # Wait for deployments to be ready
    - name: Wait for Deployments
      run: |
        kubectl rollout status deployment/prometheus -n $NAMESPACE
        kubectl rollout status deployment/grafana -n $NAMESPACE

    # Verify services are running
    - name: Verify Services
      run: |
        kubectl get pods -n $NAMESPACE -l app=prometheus
        kubectl get pods -n $NAMESPACE -l app=grafana
