name: Deploy Minimal Pod Monitoring
on:
  workflow_dispatch:

env:
  GKE_CLUSTER_NAME: receipt-dev-cluster
  GKE_REGION: us-central1
  NAMESPACE: dev

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: eadtud
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_REGION

    # Deploy main monitoring stack
    - name: Deploy Monitoring Stack
      run: |
        kubectl apply -f graphana-prometheus-stack.yaml -n $NAMESPACE

    # Add Grafana datasource configuration
    - name: Configure Grafana Datasource
      run: |
        cat <<EOF | kubectl apply -n $NAMESPACE -f -
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: grafana-datasources
          labels:
            app: grafana
        data:
          datasources.yaml: |-
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://prometheus-service:9090
              isDefault: true
              version: 1
              editable: false
              jsonData:
                timeInterval: "30s"
                httpMethod: GET
                queryTimeout: "60s"
        EOF

    # Add dashboard provider configuration
    - name: Configure Dashboard Provider
      run: |
        cat <<EOF | kubectl apply -n $NAMESPACE -f -
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: grafana-dashboard-provider
          labels:
            app: grafana
        data:
          dashboard-provider.yaml: |-
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards
        EOF

    # Add additional Grafana dashboards
    - name: Deploy Additional Grafana Dashboards
      run: |
        cat <<EOF | kubectl apply -n $NAMESPACE -f -
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: grafana-dashboards
          labels:
            app: grafana
        data:
          pod-status.json: |-
            {
              "annotations": {
                "list": []
              },
              "editable": true,
              "fiscalYearStartMonth": 0,
              "graphTooltip": 0,
              "id": null,
              "links": [],
              "liveNow": false,
              "panels": [
                {
                  "datasource": {
                    "type": "prometheus",
                    "uid": "prometheus"
                  },
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "thresholds"
                      },
                      "mappings": [],
                      "thresholds": {
                        "mode": "absolute",
                        "steps": [
                          {
                            "color": "red",
                            "value": null
                          },
                          {
                            "color": "green",
                            "value": 1
                          }
                        ]
                      }
                    },
                    "overrides": []
                  },
                  "gridPos": {
                    "h": 8,
                    "w": 24,
                    "x": 0,
                    "y": 0
                  },
                  "id": 1,
                  "options": {
                    "colorMode": "value",
                    "graphMode": "area",
                    "justifyMode": "auto",
                    "orientation": "auto",
                    "reduceOptions": {
                      "calcs": [
                        "lastNotNull"
                      ],
                      "fields": "",
                      "values": false
                    },
                    "textMode": "auto"
                  },
                  "pluginVersion": "8.5.5",
                  "targets": [
                    {
                      "datasource": {
                        "type": "prometheus",
                        "uid": "prometheus"
                      },
                      "editorMode": "code",
                      "expr": "up{job=~\"receipt-backend|receipt-frontend\"}",
                      "legendFormat": "{{pod}}",
                      "range": true,
                      "refId": "A"
                    }
                  ],
                  "title": "Pod Status Overview",
                  "type": "stat"
                }
              ],
              "refresh": "5s",
              "schemaVersion": 38,
              "style": "dark",
              "tags": [
                "kubernetes",
                "pods"
              ],
              "templating": {
                "list": []
              },
              "time": {
                "from": "now-6h",
                "to": "now"
              },
              "timepicker": {},
              "timezone": "browser",
              "title": "Pod Status Monitor",
              "uid": "pod-status",
              "version": 1,
              "weekStart": ""
            }
        EOF

    # Wait for deployments to be ready
    - name: Wait for Deployments
      run: |
        kubectl rollout status deployment/prometheus -n $NAMESPACE
        kubectl rollout status deployment/grafana -n $NAMESPACE

    # Verify services are running
    - name: Verify Services
      run: |
        kubectl get pods -n $NAMESPACE -l app=prometheus
        kubectl get pods -n $NAMESPACE -l app=grafana

    # Restart Grafana to apply new configurations
    - name: Restart Grafana
      run: |
        kubectl rollout restart deployment/grafana -n $NAMESPACE
        kubectl rollout status deployment/grafana -n $NAMESPACE

    # Clean up any duplicate datasources
    - name: Clean up duplicate datasources
      run: |
        kubectl delete configmap grafana-datasource-provider -n $NAMESPACE --ignore-not-found=true
        kubectl delete configmap grafana-provisioning-datasources -n $NAMESPACE --ignore-not-found=true
